---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - '/.github/workflows'
      - '/.github/actions/**/*'
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"
