#!/usr/bin/with-contenv sh

init_host_key() {
  # generate host keys if not present
  ssh-keygen -A
}

init_root_password() {
  # set root password
  if [ -n "$ROOT_PASSWORD" ]; then
    echo "root:$ROOT_PASSWORD" | chpasswd
  fi;
}

init_authorized_keys() {
  # set authorized keys
  if [ -n "$AUTHORIZED_KEYS" ]; then
    mkdir ~/.ssh
    chown root:root ~/.ssh && chmod 700 ~/.ssh/

    echo "$AUTHORIZED_KEYS" > ~/.ssh/authorized_keys

    chown root:root ~/.ssh/authorized_keys
    chmod 600 ~/.ssh/authorized_keys
  fi
}

init_host_key
init_root_password
init_authorized_keys
